// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListFiles(arg1) {
  return window['go']['main']['App']['ListFiles'](arg1);
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function ReadBinaryFile(arg1) {
  return window['go']['main']['App']['ReadBinaryFile'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}
