// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ListFiles(arg1:string):Promise<Array<main.FileInfo>>;

export function OpenFolder():Promise<string>;

export function ReadBinaryFile(arg1:string):Promise<Array<number>>;

export function ReadTextFile(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;
